name: CD Pipeline (Train & Deploy)

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *' # Запуск каждый день в 2:00 UTC
  workflow_dispatch: # Возможность ручного запуска

jobs:
  train-and-deploy:
    if: false
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install sagemaker

      - name: Run MLOps Pipeline
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_auth: ${{ secrets.MLFLOW_BASIC_AUTH }} # Если нужно передать auth
        run: |
          # Запуск вашего Python скрипта-оркестратора
          python pipelines/run_pipeline.py --stage production